[build]
  command = "cd finance-grades-pwa && npm install && npm run build"
  publish = "finance-grades-pwa/dist/finance-grades-pwa/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
